from django.urls import path
from .views import *

urlpatterns = [
    path('api/logoget/', LogoGET.as_view()),
    path('api/logopost/', LogoPOST),
    path('api/infoget/', InfoGET.as_view()),
    path('api/infopost/', InfoPOST),
    path('api/sliderget/', SliderGET.as_view()),
    path('api/sliderpost/', SliderPOST),
    path('api/categoryget/', CategoryGET.as_view()),
    path('api/categorypost/', CategoryPOST),
    path('api/productget/', ProductGET.as_view()),
    path('api/productpost/', ProductPOST),
    path('api/product/<int:pk>/', ProductReveiw.as_view()),
    path('api/wishlistget/', WishlistGET.as_view()),
    path('api/wishlistpost/', WishlistPOST),
    path('api/wishlist/product/<int:pk>', WishlistReveiw.as_view()),
    path('api/cardget/', CardGET.as_view()),
    path('api/cardpost/', CardPOST),
    path('api/card/product/<int:pk>', CardReveiw.as_view()),
    path('api/purchaseget/', PurchaseGET.as_view()),
    path('api/purchasepost/', PurchasePOST),
    path('api/facilitiesget/', FacilitiesGET.as_view()),
    path('api/facilitiespost/', FacilitiesPOST),
    path('api/forsaleget/', ForsaleGET.as_view()),
    path('api/forsalepost/', ForsalePOST),
    path('api/bestsellget/', BestsellGET.as_view()),
    path('api/latestblogget/', LatestblogGET.as_view()),
    path('api/latestblogpost/', LatestblogPOST),
    path('api/newsletterget/', NewsletterPOST.as_view()),
    path('api/newsletterpost/', NewsletterGET),
    path('api/teammembersget/', TeamMembersGET.as_view()),
    path('api/teammemberspost/', TeamMembersPOST),
    path('api/clientget/', ClientGET.as_view()),
    path('api/clientpost/', ClientPOST),
    path('api/sponsorget/', SponsorGET.as_view()),
    path('api/sponsorpost/', SponsorPOST),
    path('api/leavemsgget/', LeaveMsgGET),
    path('api/leavemsgpost/', LeaveMsgPOST.as_view()),
    path('api/mapget/', MapGET.as_view()),
    path('api/mappost/', MapPOST),
    path('api/search/', Search),
]